### ISSUE TITLE
Address db connection timeouts

### ISSUE THREAD

**Issue by jc00ke** [RatioPBC/epi-contacts#16]
```javascript
{
    "time": "2021-12-28T10:00:04.426Z",
    "severity": "error",
    "message": "#PID<0.13019.553> running EpiContactsWeb.Endpoint (connection #PID<0.12556.553>, stream id 12) terminated\nServer: share-my-contacts.health.ny.gov:80 (http)\nRequest: POST /api/commcare/forwarding\n** (exit) an exception was raised:\n    ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 230ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available and that you can connect to it\n  2. Tracking down slow queries and making sure they are running fast enough\n  3. Increasing the pool_size (albeit it increases resource consumption)\n  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n\n        (db_connection 2.4.0) lib/db_connection.ex:883: DBConnection.transaction/3\n        (oban 2.8.0) lib/oban/query.ex:15: Oban.Query.fetch_or_insert_job/2\n        (oban 2.8.0) lib/oban.ex:269: Oban.insert!/2\n        (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:7: EpiContactsWeb.CommcareApiController.webhook/2\n        (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:1: EpiContactsWeb.CommcareApiController.action/2\n        (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:1: EpiContactsWeb.CommcareApiController.phoenix_controller_pipeline/2\n        (phoenix 1.5.9) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n        (epi_contacts 0.1.0) lib/plug/error_handler.ex:80: EpiContactsWeb.Router.call/2",
    "metadata": {
        "conn": {
            "adapter": {
                "Elixir.Plug.Cowboy.Conn": {
                    "bindings": {},
                    "body_length": 2276,
                    "cert": "undefined",
                    "has_body": true,
                    "headers": {
                        "accept": "*/*",
                        "accept-encoding": "gzip, deflate",
                        "authorization": "Basic [REDACTED]",
                        "content-length": "2276",
                        "content-type": "application/json",
                        "host": "share-my-contacts.health.ny.gov",
                        "sentry-trace": "80ec3c4ebaa6425dab822e47f3b38993-8dc90646950c1fe0-0",
                        "server-modified-on": "2021-12-28T14:59:39.286243Z",
                        "user-agent": "python-requests/2.25.1",
                        "x-amzn-trace-id": "Root=1-61cb2674-331cdad72553840b5962fd84",
                        "x-forwarded-for": "35.175.35.59",
                        "x-forwarded-port": "443",
                        "x-forwarded-proto": "https"
                    },
                    "host": "share-my-contacts.health.ny.gov",
                    "host_info": "undefined",
                    "method": "POST",
                    "path": "/api/commcare/forwarding",
                    "path_info": "undefined",
                    "peer": [
                        [
                            10,
                            50,
                            1,
                            100
                        ],
                        33674
                    ],
                    "pid": "#PID<0.12556.553>",
                    "port": 80,
                    "qs": "",
                    "ref": "Elixir.EpiContactsWeb.Endpoint.HTTP",
                    "scheme": "http",
                    "sock": [
                        [
                            10,
                            50,
                            115,
                            155
                        ],
                        4000
                    ],
                    "streamid": 12,
                    "version": "HTTP/1.1"
                }
            },
            "assigns": {},
            "body_params": {
                "aspect": "body_params"
            },
            "cookies": {
                "aspect": "cookies"
            },
            "halted": false,
            "host": "share-my-contacts.health.ny.gov",
            "method": "POST",
            "owner": "#PID<0.13019.553>",
            "params": {
                "aspect": "params"
            },
            "path_info": [
                "api",
                "commcare",
                "forwarding"
            ],
            "path_params": {},
            "port": 80,
            "private": {},
            "query_params": {
                "aspect": "query_params"
            },
            "query_string": "",
            "remote_ip": [
                10,
                50,
                1,
                100
            ],
            "req_cookies": {
                "aspect": "cookies"
            },
            "req_headers": [
                {
                    "accept": "*/*"
                },
                {
                    "accept-encoding": "gzip, deflate"
                },
                {
                    "authorization": "Basic [REDACTED]"
                },
                {
                    "content-length": "2276"
                },
                {
                    "content-type": "application/json"
                },
                {
                    "host": "share-my-contacts.health.ny.gov"
                },
                {
                    "sentry-trace": "80ec3c4ebaa6425dab822e47f3b38993-8dc90646950c1fe0-0"
                },
                {
                    "server-modified-on": "2021-12-28T14:59:39.286243Z"
                },
                {
                    "user-agent": "python-requests/2.25.1"
                },
                {
                    "x-amzn-trace-id": "Root=1-61cb2674-331cdad72553840b5962fd84"
                },
                {
                    "x-forwarded-for": "35.175.35.59"
                },
                {
                    "x-forwarded-port": "443"
                },
                {
                    "x-forwarded-proto": "https"
                }
            ],
            "request_path": "/api/commcare/forwarding",
            "resp_body": null,
            "resp_cookies": {},
            "resp_headers": [
                {
                    "cache-control": "max-age=0, private, must-revalidate"
                }
            ],
            "scheme": "http",
            "script_name": [],
            "secret_key_base": null,
            "state": "unset",
            "status": null
        },
        "domain": [
            "cowboy"
        ],
        "erl_level": "error",
        "error": {
            "initial_call": null,
            "reason": "** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 230ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available and that you can connect to it\n  2. Tracking down slow queries and making sure they are running fast enough\n  3. Increasing the pool_size (albeit it increases resource consumption)\n  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n\n    (db_connection 2.4.0) lib/db_connection.ex:883: DBConnection.transaction/3\n    (oban 2.8.0) lib/oban/query.ex:15: Oban.Query.fetch_or_insert_job/2\n    (oban 2.8.0) lib/oban.ex:269: Oban.insert!/2\n    (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:7: EpiContactsWeb.CommcareApiController.webhook/2\n    (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:1: EpiContactsWeb.CommcareApiController.action/2\n    (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:1: EpiContactsWeb.CommcareApiController.phoenix_controller_pipeline/2\n    (phoenix 1.5.9) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2\n    (epi_contacts 0.1.0) lib/plug/error_handler.ex:80: EpiContactsWeb.Router.call/2\n"
        },
        "error_logger": {
            "tag": "error"
        }
    }
}

```

formatted error:

```
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 230ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (albeit it increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (db_connection 2.4.0) lib/db_connection.ex:883: DBConnection.transaction/3
    (oban 2.8.0) lib/oban/query.ex:15: Oban.Query.fetch_or_insert_job/2
    (oban 2.8.0) lib/oban.ex:269: Oban.insert!/2
    (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:7: EpiContactsWeb.CommcareApiController.webhook/2
    (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:1: EpiContactsWeb.CommcareApiController.action/2
    (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:1: EpiContactsWeb.CommcareApiController.phoenix_controller_pipeline/2
    (phoenix 1.5.9) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
    (epi_contacts 0.1.0) lib/plug/error_handler.ex:80: EpiContactsWeb.Router.call/2
```

**Comment by jc00ke** [comment]
Running

```sql
select * from pg_settings where name='max_connections';
```

returned a `setting` of 405, so we should be safe to bump to 50 for sure. I believe we can set this in AWS Secrets Manager with `POOL_SIZE`.

**Comment by jc00ke** [comment]
We're still seeing this after bumping the pool size to 60 :confused: 

```javascript
{
    "time": "2022-01-06T19:50:54.840Z",
    "severity": "error",
    "message": "#PID<0.15330.2> running EpiContactsWeb.Endpoint (connection #PID<0.15128.2>, stream id 29) terminated\nServer: share-my-contacts.health.ny.gov:80 (http)\nRequest: POST /api/commcare/forwarding\n** (exit) an exception was raised:\n    ** (DBConnection.ConnectionError) ssl recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)\n        (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1\n        (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4\n        (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4\n        (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4\n        (db_connection 2.4.1) lib/db_connection.ex:1531: DBConnection.run_transaction/4\n        (oban 2.10.1) lib/oban/query.ex:16: Oban.Query.fetch_or_insert_job/2\n        (oban 2.10.1) lib/oban.ex:274: Oban.insert!/2\n        (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:7: EpiContactsWeb.CommcareApiController.webhook/2",
    "metadata": {
        "conn": {
            "adapter": {
                "Elixir.Plug.Cowboy.Conn": {
                    "bindings": {},
                    "body_length": 4176,
                    "cert": "undefined",
                    "has_body": true,
                    "headers": {
                        "accept": "*/*",
                        "accept-encoding": "gzip, deflate",
                        "authorization": "Basic [REDACTED]",
                        "content-length": "4176",
                        "content-type": "application/json",
                        "host": "share-my-contacts.health.ny.gov",
                        "sentry-trace": "db3fb0c2b1464fd1b1020a48e009354a-860baeb5c092f2ce-0",
                        "server-modified-on": "2022-01-07T00:50:39.549427Z",
                        "user-agent": "python-requests/2.25.1",
                        "x-amzn-trace-id": "Root=1-61d78e5f-31ca93ad4edd17d21fbf17cb",
                        "x-forwarded-for": "35.175.35.59",
                        "x-forwarded-port": "443",
                        "x-forwarded-proto": "https"
                    },
                    "host": "share-my-contacts.health.ny.gov",
                    "host_info": "undefined",
                    "method": "POST",
                    "path": "/api/commcare/forwarding",
                    "path_info": "undefined",
                    "peer": [
                        [
                            10,
                            50,
                            0,
                            162
                        ],
                        48416
                    ],
                    "pid": "#PID<0.15128.2>",
                    "port": 80,
                    "qs": "",
                    "ref": "Elixir.EpiContactsWeb.Endpoint.HTTP",
                    "scheme": "http",
                    "sock": [
                        [
                            10,
                            50,
                            78,
                            115
                        ],
                        4000
                    ],
                    "streamid": 29,
                    "version": "HTTP/1.1"
                }
            },
            "assigns": {},
            "body_params": {
                "aspect": "body_params"
            },
            "cookies": {
                "aspect": "cookies"
            },
            "halted": false,
            "host": "share-my-contacts.health.ny.gov",
            "method": "POST",
            "owner": "#PID<0.15330.2>",
            "params": {
                "aspect": "params"
            },
            "path_info": [
                "api",
                "commcare",
                "forwarding"
            ],
            "path_params": {},
            "port": 80,
            "private": {},
            "query_params": {
                "aspect": "query_params"
            },
            "query_string": "",
            "remote_ip": [
                10,
                50,
                0,
                162
            ],
            "req_cookies": {
                "aspect": "cookies"
            },
            "req_headers": [
                {
                    "accept": "*/*"
                },
                {
                    "accept-encoding": "gzip, deflate"
                },
                {
                    "authorization": "Basic [REDACTED]"
                },
                {
                    "content-length": "4176"
                },
                {
                    "content-type": "application/json"
                },
                {
                    "host": "share-my-contacts.health.ny.gov"
                },
                {
                    "sentry-trace": "db3fb0c2b1464fd1b1020a48e009354a-860baeb5c092f2ce-0"
                },
                {
                    "server-modified-on": "2022-01-07T00:50:39.549427Z"
                },
                {
                    "user-agent": "python-requests/2.25.1"
                },
                {
                    "x-amzn-trace-id": "Root=1-61d78e5f-31ca93ad4edd17d21fbf17cb"
                },
                {
                    "x-forwarded-for": "35.175.35.59"
                },
                {
                    "x-forwarded-port": "443"
                },
                {
                    "x-forwarded-proto": "https"
                }
            ],
            "request_path": "/api/commcare/forwarding",
            "resp_body": null,
            "resp_cookies": {},
            "resp_headers": [
                {
                    "cache-control": "max-age=0, private, must-revalidate"
                }
            ],
            "scheme": "http",
            "script_name": [],
            "secret_key_base": null,
            "state": "unset",
            "status": null
        },
        "domain": [
            "cowboy"
        ],
        "erl_level": "error",
        "error": {
            "initial_call": null,
            "reason": "** (DBConnection.ConnectionError) ssl recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)\n    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1\n    (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4\n    (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4\n    (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4\n    (db_connection 2.4.1) lib/db_connection.ex:1531: DBConnection.run_transaction/4\n    (oban 2.10.1) lib/oban/query.ex:16: Oban.Query.fetch_or_insert_job/2\n    (oban 2.10.1) lib/oban.ex:274: Oban.insert!/2\n    (epi_contacts 0.1.0) lib/epi_contacts_web/controllers/commcare_api_controller.ex:7: EpiContactsWeb.CommcareApiController.webhook/2\n"
        },
        "error_logger": {
            "tag": "error"
        }
    }
}
```

**Comment by jc00ke** [comment]
I'm wondering if the database needs some love? We could stand to prune old jobs, especially discarded ones, and bump not only PG version but also the server itself. I'm not able to load the Oban Web dashboard now.

```javascript
{
    "time": "2022-01-07T13:37:19.508Z",
    "severity": "error",
    "message": "Postgrex.Protocol (#PID<0.5079.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5286.0> timed out because it queued and checked out the connection for longer than 15000ms\n\n#PID<0.5286.0> was at location:\n\n    (stdlib 3.17) gen.erl:214: :gen.do_call/4\n    (stdlib 3.17) gen_statem.erl:693: :gen_statem.call_dirty/4\n    (ssl 10.6) ssl_gen_statem.erl:1187: :ssl_gen_statem.call/2\n    (postgrex 0.15.13) lib/postgrex/protocol.ex:2996: Postgrex.Protocol.msg_recv/4\n    (postgrex 0.15.13) lib/postgrex/protocol.ex:2712: Postgrex.Protocol.recv_transaction/4\n    (db_connection 2.4.1) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4\n    (db_connection 2.4.1) lib/db_connection.ex:1654: DBConnection.run_commit/3\n    (db_connection 2.4.1) lib/db_connection.ex:1141: DBConnection.checkin/4\n",
    "metadata": {
        "domain": [
            "elixir"
        ],
        "erl_level": "error"
    }
}
```
